apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-single
  namespace: efk
  labels:
    k8s-app: kibana-single
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-single
  template:
    metadata:
      labels:
        k8s-app: kibana-single
    spec:
      containers:
      - name: kibana-single
        image: kibana:7.12.0
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 0.5 
            memory: 500Mi
        env:
          - name: ELASTICSEARCH_HOSTS
#指定elasticsearch的servicesname，记得加上命名空间.ops
            value: http://elasticsearch-single.efk:9200
          - name: I18N_LOCALE
            value: zh-CN
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-single
  namespace: efk
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
    nodePort: 30606
  selector:
    k8s-app: kibana-single
