---
#- name: 在线下载
#  shell: curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 分发并解压docker-compose二进制包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/docker-compose-*.tar.gz"

- name: +x 执行权限
  shell: chmod +x  {{ tmp_dir }}/docker-compose

- name: 移动docker二进制文件
  shell: cp -rf {{ tmp_dir }}/docker-compose /usr/local/bin/

- name: 软连接
  ignore_errors: yes
  shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

- name: 查看状态
  shell: docker-compose --version
  register: docker_compose
- debug: var=docker_compose.stdout_lines
