---
# 这个剧本在所有节点上运行



- name: 关闭 firewalld
  service: name=firewalld state=stopped enabled=no

- name: 清空 iptables
  shell: iptables -F

- name: 关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  
- name: 关闭 swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 即时生效，selinux 和 swap，无需重启
  shell: setenforce 0 ; swapoff -a; timedatectl set-timezone "Asia/Shanghai"

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime


- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts 

- name: 同步系统时间
  yum: name=ntpdate state=present
- name: 同步系统时间
  shell: ntpdate time.windows.com

- name: 获取Ansible工作目录
  shell: pwd |sed 's#roles/tls##' 
  register: root_dir 

- name: 创建工作目录
  file: dest={{ root_dir.stdout }}/ssl/{{ item }} state=directory
  with_items:
    - etcd
    - k8s